config/routes.rb
Rails.application.routes.draw do

  root 'pages#accueil'

  get 'profil' => 'pages#profil'
  get 'moncv' => 'pages#moncv'
  get 'projets' => 'pages#projets'
  get 'contact' => 'pages#contact'
  resources :contacts, only: [:new, :create]

  #Telechargement pdf
  get "download_pdf" => 'pages#download_pdf'


end

app/models/contact.rb
class Contact < MailForm::Base

  attribute :name,      :validate => true
  attribute :email,     :validate => /\A([\w\.%\+\-]+)@([\w\-]+\.)+([\w]{2,})\z/i
  attribute :message
  attribute :telephone

  # Declare the e-mail headers. It accepts anything the mail method
  # in ActionMailer accepts.
  def headers
    {
      :subject => "Formulaire de contact site perso",
      :to => "eric.merlin3@gmail.com",
      :from => %("#{name}" <#{email}>)
    }
  end

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/contacts_controller.rb
class ContactsController < ApplicationController

  def new
    @contact = Contact.new
  end

  def create
    @contact = Contact.new(params[:contact])
    @contact.request = request
      if @contact.deliver
        flash.now[:error] = nil
      else
        flash.now[:error] = 'Cannot send message.'
        render :new
      end
  end

end

app/controllers/pages_controller.rb
class PagesController < ApplicationController

  def accueil
    @titre = "Accueil"
  end

  def profil
    @titre = "Profil"
  end

  def moncv
    @titre = "Mon Cv"
  end

  def projets
    @titre = "Mes Projets"
  end

  def contact
    @titre = "Contact"
  end

  # Envoi du cv en pdf
  def download_pdf
  send_file(
    "#{Rails.root}/public/cv_eric_merlin.pdf",
    filename: "cv_eric_merlin.pdf",
    type: "application/pdf"
  )
end

end

app/helpers/application_helper.rb
module ApplicationHelper

  # Affiche automatiquement le nom de la page courante
  def titre
    base_titre = "Merlin Eric"
    if @titre.nil?
      base_titre
    else
      "#{base_titre} | #{@titre}"
    end
  end

end

app/helpers/contacts_helper.rb
module ContactsHelper
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/views/contacts/create.html.erb
<h2>Votre message a bien été envoyé !!!</h2>

app/views/contacts/new.html.erb
<article class="common-inner animated clearfix" id="contact">
  <div class="common-image">
    <div class="image-cont"><%= image_tag("eric.jpg") %></div>
  </div>
  <div class="profile-cont">
    <div class="profile-top">
      <h2>Bonjour, je suis <span>Eric Merlin</span></h2>
      <h3>Mon profil vous interresse ? Prenons un café !</h3>
      <ul class="social">
        <li><%= link_to "<i class='fa fa-github'></i>".html_safe, 'https://github.com/riquet28', :target => "_blank" %></li>
        <li><%= link_to "<i class='fa fa-linkedin'></i>".html_safe, 'https://fr.linkedin.com/in/eric-merlin-563464101', :target => "_blank" %></li>
      </ul>
    </div>
    <div class="row profile-middle-content clearfix">
      <div class="col-md-12 contact-map">
        <iframe src="https://www.google.com/maps/embed?pb=!1m23!1m12!1m3!1d674441.3347148045!2d2.011946198960166!3d48.67610713330099!2m3!1f0!2f0!3f0!3m2!1i1024!2i768!4f13.1!4m8!3e6!4m0!4m5!1s0x47e38e6d9d3d671b%3A0x40dc8d705397e60!2s28120+Illiers-Combray%2C+France!3m2!1d48.299426999999994!2d1.2453509999999999!5e0!3m2!1sfr!2sus!4v1453227020232" width="100%" height="100%" frameborder="0" style="border:0" allowfullscreen></iframe>
      </div>
      <div class="col-md-12 contact-form">
        <h3>M'envoyer un message</h3>
        <div id="contact-form">
          <%= form_for @contact do |f| %>
            <%= f.text_field :name, required: true, id:"contact-name", class: "your-name", placeholder: "Votre Nom" %>

            <%= f.email_field :email, required: true, class: "your-email", id: "contact-email", placeholder: "Votre Email" %>

            <%= f.text_field :telephone, required: true, class: "your-phone", id: "contact-phone", placeholder: "Votre Téléphone"  %>

            <%= f.text_area :message, as: :text, id: "contact-msg", class: "your-message", placeholder: "Votre Message" %>


            <%= f.submit 'Envoyer', id: "contact-submit", class: "submit-btn" %>

          <% end %>
        </div>
      </div>
      <div class="col-md-12 contact-adress">
        <h3>Contact info</h3>
        <p><b>Téléphone :</b> 06.26.63.31.47</p>
        <p><b>Email :</b> <a href="mailto:eric.merlin3@gmail.com">eric.merlin3@gmail.com</a></p>
      </div>
    </div>
  </div>
</article>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
    <head>
      <title><%= titre %></title>
      <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
      <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
      <%= csrf_meta_tags %>
      <meta name="viewport" content="width=device-width, initial-scale=1.0">
    </head>

    <body>

    <div id="tab-container">

      <%= render 'shared/header' %>

      <section class="full-page-cont clearfix">
        <div class="container">
          <div class="row">

          <%= yield %>

          </div>
        </div>
      </section>

      <%= render 'shared/footer' %>

    </div>

  </body>
</html>

app/views/pages/_competences.html.erb
<div class="col-md-4">
        <div class="skill-area">
          <h5>Compétences Web</h5>
          <hr>
          <div>
            <ul class="skill-dots">
              <li>
                <span class="title">Rails</span> <span class="filled"></span> <span class="filled"></span> <span class="filled"></span> <span class="filled"></span> <span class="filled"></span> <span class="filled"></span> <span class="filled"></span> <span class="transparent"></span> <span class="transparent"></span> <span class="transparent"></span>
              </li>
              <li>
                <span class="title">Ruby</span> <span class="filled"></span> <span class="filled"></span> <span class="filled"></span> <span class="filled"></span> <span class="filled"></span> <span class="filled"></span> <span class="transparent"></span> <span class="transparent"></span> <span class="transparent"></span> <span class="transparent"></span>
              </li>
              <li>
                <span class="title">ReactRB(new)</span> <span class="filled"></span> <span class="filled"></span> <span class="filled"></span> <span class="filled"></span> <span class="filled"></span> <span class="transparent"></span> <span class="transparent"></span> <span class="transparent"></span> <span class="transparent"></span> <span class="transparent"></span>
              </li>
              <li>
                <span class="title">html</span> <span class="filled"></span> <span class="filled"></span> <span class="filled"></span> <span class="filled"></span> <span class="filled"></span> <span class="filled"></span> <span class="filled"></span> <span class="filled"></span> <span class="transparent"></span> <span class="transparent"></span>
              </li>
              <li>
                <span class="title">css</span> <span class="filled"></span> <span class="filled"></span> <span class="filled"></span> <span class="filled"></span> <span class="filled"></span> <span class="filled"></span> <span class="filled"></span> <span class="filled"></span> <span class="transparent"></span> <span class="transparent"></span>
              </li>
              <li>
                <span class="title">Bootstrap</span> <span class="filled"></span> <span class="filled"></span> <span class="filled"></span> <span class="filled"></span> <span class="filled"></span> <span class="filled"></span> <span class="filled"></span> <span class="filled"></span> <span class="transparent"></span> <span class="transparent"></span>
              </li>
              <li>
                <span class="title">LocomotiveCms</span> <span class="filled"></span> <span class="filled"></span> <span class="filled"></span> <span class="filled"></span> <span class="filled"></span> <span class="filled"></span> <span class="filled"></span> <span class="transparent"></span> <span class="transparent"></span> <span class="transparent"></span>
              </li>
            </ul>
          </div>
        </div>
        <div class="skill-area">
          <h5>Outils Web</h5>
          <hr>
          <div>
            <ul class="skill-dots">
              <li> <span class="title">Github</span> <span class="filled"></span> <span class="filled"></span> <span class="filled"></span> <span class="filled"></span> <span class="filled"></span> <span class="filled"></span> <span class="filled"></span> <span class="transparent"></span> <span class="transparent"></span> <span class="transparent"></span> </li>
              <li> <span class="title">Scrum</span> <span class="filled"></span> <span class="filled"></span> <span class="filled"></span> <span class="filled"></span> <span class="filled"></span> <span class="filled"></span> <span class="filled"></span> <span class="filled"></span> <span class="transparent"></span> <span class="transparent"></span> </li>
              <li> <span class="title">Waffle</span> <span class="filled"></span> <span class="filled"></span> <span class="filled"></span> <span class="filled"></span> <span class="filled"></span> <span class="filled"></span> <span class="filled"></span> <span class="transparent"></span> <span class="transparent"></span> <span class="transparent"></span> </li>
              <li> <span class="title">Linux</span> <span class="filled"></span> <span class="filled"></span> <span class="filled"></span> <span class="filled"></span> <span class="filled"></span> <span class="transparent"></span> <span class="transparent"></span> <span class="transparent"></span> <span class="transparent"></span> <span class="transparent"></span> </li>
            </ul>
          </div>
        </div>
        <div class="skill-area">
          <h5>Langues</h5>
          <hr>
          <div>
            <ul class="skill-dots">
              <li>
                <span class="title">Anglais</span> <span class="filled"></span> <span class="filled"></span> <span class="filled"></span> <span class="filled"></span> <span class="filled"></span> <span class="transparent"></span> <span class="transparent"></span> <span class="transparent"></span> <span class="transparent"></span> <span class="transparent"></span>
              </li>
              <li>
                <span class="title">Espagnol</span> <span class="filled"></span> <span class="filled"></span> <span class="filled"></span> <span class="transparent"></span> <span class="transparent"></span> <span class="transparent"></span> <span class="transparent"></span> <span class="transparent"></span> <span class="transparent"></span> <span class="transparent"></span>
              </li>
            </ul>
          </div>
        </div>
      </div>

app/views/pages/accueil.html.erb
<article class="home-page animated" id="home">
  <div class="row">
    <div class="col-md-6 home-profile">
      <div class="home-profile-image">
        <%= image_tag("eric.jpg") %>
      </div>
      <div class="home-profile-quick">
        <h4>Information</h4>
        <p>Obtention du titre de<br>Développeur logiciel - Niveau III<br>depuis le 09 décembre 2016
        </p>
        <%= link_to "<i class='fa fa-eye'></i>      VOIR MON PROFIL".html_safe, profil_path, class: "view-profile" %>
      </div>
    </div>
    <div class="col-md-6 home-details">
      <h1><span>Bonjour, je suis</span><br>Eric Merlin</h1>
      <h2>Web développeur Fullstack Ruby on Rails</h2>
      <hr>
      <p class="medium"><i>Demain ne sera pas comme hier. Il sera nouveau et dépendra de nous.<br>Il est moins à découvrir qu'à inventer. (Gaston Berger)</i></p>
      <ul class="social">
        <li><%= link_to "<i class='fa fa-github'></i>".html_safe, 'https://github.com/riquet28', :target => "_blank" %></li>
        <li><%= link_to "<i class='fa fa-linkedin'></i>".html_safe, 'https://fr.linkedin.com/in/eric-merlin-563464101', :target => "_blank" %></li>
      </ul>
    </div>
    <div class="col-md-12 skill-home">
      <div class="skill-home-solid clearfix">
        <div class="col-md-3">
          <h2>Parmis mes<br><span>compétences</span></h2>
        </div>
        <div class="col-md-3 text-center"> <span class="icons"><i class="fa fa-code"></i></span>
          <h3>Programmation Web</h3>
          <p>Ruby, Ruby on Rails et prochainement jQuery et Javascript ...</p>
        </div>
        <div class="col-md-3 text-center"> <span class="icons"><i class="fa fa-html5"></i></span>
          <h3>Intégration Web</h3>
          <p>Html5, Css3, Twitter-Bootstrap, Sass, Compas ...</p>
        </div>
        <div class="col-md-3 text-center"> <span class="icons"><i class="fa fa-wrench"></i></span>
          <h3>Outils Web</h3>
          <p>Git et Github, Waffle, Stackoverflow ...</p>
        </div>
      </div>
    </div>
  </div>
</article>

app/views/pages/contact.html.erb
<article class="common-inner animated clearfix" id="contact">
  <div class="common-image">
    <div class="image-cont"><%= image_tag("eric.jpg") %></div>
  </div>
  <div class="profile-cont">
    <div class="profile-top">
      <h2>Bonjour, je suis <span>Eric Merlin</span></h2>
      <h3>Mon profil vous interresse ? Prenons un café !</h3>
      <ul class="social">
        <li><%= link_to "<i class='fa fa-github'></i>".html_safe, 'https://github.com/riquet28', :target => "_blank" %></li>
        <li><%= link_to "<i class='fa fa-linkedin'></i>".html_safe, 'https://fr.linkedin.com/in/eric-merlin-563464101', :target => "_blank" %></li>
      </ul>
    </div>
    <div class="row profile-middle-content clearfix">
      <div class="col-md-12 contact-map">
        <iframe src="https://www.google.com/maps/embed?pb=!1m23!1m12!1m3!1d674441.3347148045!2d2.011946198960166!3d48.67610713330099!2m3!1f0!2f0!3f0!3m2!1i1024!2i768!4f13.1!4m8!3e6!4m0!4m5!1s0x47e38e6d9d3d671b%3A0x40dc8d705397e60!2s28120+Illiers-Combray%2C+France!3m2!1d48.299426999999994!2d1.2453509999999999!5e0!3m2!1sfr!2sus!4v1453227020232" width="100%" height="100%" frameborder="0" style="border:0" allowfullscreen></iframe>
      </div>
      <div class="col-md-12 contact-form">
        <h3>M'envoyer un message</h3>
        <form name="contact" method="post">
          <div id="contact-form">
            <input type="text" name="name" id="contact-name" class="your-name" placeholder="Votre Nom (Non encore fonctionnel)">
            <input type="text" name="email" class="your-email" id="contact-email" placeholder="Votre Email (Non encore fonctionnel)">
            <input type="text" name="phone" class="your-phone" id="contact-phone" placeholder="Votre Téléphone (Non encore fonctionnel)">
            <textarea cols="10" rows="4" name="message" id="contact-msg" class="your-message" placeholder="Votre Message (Messagerie non encore fonctionnel, veuillez utiliser le lien ci-dessous)"></textarea>
            <button type="submit" id="contact-submit" name="submit" class="submit-btn">Envoyer</button>
          </div>
        </form>
      </div>
      <div class="col-md-12 contact-adress">
        <h3>Contact info</h3>
        <p><b>Téléphone :</b> 06.26.63.31.47</p>
        <p><b>Email :</b> <a href="mailto:eric.merlin3@gmail.com">eric.merlin3@gmail.com</a></p>
      </div>
    </div>
  </div>
</article>

app/views/pages/moncv.html.erb
<article class="common-inner animated clearfix" id="resume">
  <div class="common-image">
      <div class="image-cont"><%= image_tag("eric.jpg") %></div>
  </div>
  <div class="profile-cont">
    <div class="profile-top">
      <h2>Bonjour, je suis <span>Eric Merlin</span></h2>
      <h3>Ici vous pouvez voir mon CV</h3>
    </div>
    <div class="row profile-middle-content clearfix">
      <div class="col-md-8">
        <div class="my-employment">
          <div class="my-education">
            <h3>Mes Formations</h3>
            <div class="education">
              <h4>Wild Code School – <i>Titre Développeur Logiciel - Niveau III </i></h4>
              <p>Obtention du titre de Développeur Logiciel - Niveau III le 09 décembre 2016.
              </p>
            </div>
            <div class="education">
              <h4>Wild Code School – <i>Certification Développement Web avec mention </i></h4>
              <p>Formation intensive de 5 mois. Session du 31/08/2015 au 29/01/2016. Apprentissage du code, mise en place et réalisation de projets professionnels.
              </p>
            </div>
            <div class="education">
              <h4>OpenClassroom – <i>Cours et Tutoriels </i></h4>
              <p>Afin de préparer au mieux ma formation à la Wild code School, j'ai suivi les cours d'OpenClassroom en autodidacte et obtenu plusieurs certifications telle que : "Community Manager", "Programmation avec Ruby", "Php et MySql", "Bootstrap", "Linux" et bien d'autres encore...
              </p>
            </div>
          </div>
          <h3>Mes Expériences</h3>
          <div class="employment">
            <h4>Développeur Junior (Freelance) – <i>Multi-clients [ Juin 2016 - Actuellement ]</i></h4>
            <p>Actuellement je collabore comme freelance dans differents projets, création d'applications, créations de site web, créations de site e-commerce auprès de différents clients...
            </p>
          </div>
          <div class="employment">
            <h4>Développeur Junior (Stage 4 mois) – <i>Ponéo [ Février 2016 - Juin 2016 ]</i></h4>
            <p>Reprise et poursuite de l'application commencée par d'autres étudiants de la WCS, changement d'architecture, fix des bugs, développement de nouvelles fonctionnalités, mise en place des tests et un travail de front.
            </p>
          </div>
          <div class="employment">
            <h4>Coursier – <i>West Coursiers [ 2010 - 2014 ]</i></h4>
            <p>Courses et livraisons de plis et petits colis en moto sur Paris et Ile de France. Courses ponctuelles et organisation et gestion de tournées.
            </p>
          </div>
          <div class="employment">
            <h4>Coursier – <i>Diverses Sociétés [ 1993 - 2010 ]</i></h4>
            <p>Courses et livraisons de plis et petits colis en moto sur Paris et Ile de France. Courses ponctuelles et organisation et gestion de tournées (dont 10 ans à mon compte).
            </p>
          </div>
        </div>
      </div>

      <%= render 'competences' %>

    </div>
    <%= link_to download_pdf_path, :class => "download-resume" do %>
      <span class="solid">
        <i class="fa fa-arrow-circle-down" style="margin-right: 20px;"></i>
          Télécharger <b>Mon CV</b>
        <i class="fa fa-arrow-circle-down" style="margin-left: 20px;"></i>
      </span>
    <% end %>
  </div>
</article>

app/views/pages/profil.html.erb
<article class="common-inner animated clearfix" id="profile">
  <div class="common-image">
      <div class="image-cont"><%= image_tag("eric.jpg") %></div>
  </div>
  <div class="profile-cont">
    <div class="profile-top">
      <h2>Bonjour, je suis <span>Eric Merlin</span></h2>
      <h3>Web développeur Fullstack Ruby on Rails</h3>
    </div>
    <div class="row profile-col-cont">
      <div class="col-md-4 text-center"> <span class="icons"><i class="fa fa-code"></i></span>
        <h3>Programmation Web</h3>
        <p>Ruby, Ruby on Rails et prochainement jQuery et Javascript ...</p>
      </div>
      <div class="col-md-4 text-center"> <span class="icons"><i class="fa fa-html5"></i></span>
        <h3>Intégration Web</h3>
        <p>Html5, Css3, Twitter-Bootstrap, Sass, Compas ...</p>
      </div>
      <div class="col-md-4 text-center"> <span class="icons"><i class="fa fa-wrench"></i></span>
        <h3>Outils Web</h3>
        <p>Git et Github, Waffle, Stackoverflow ...</p>
      </div>
    </div>
    <div class="row profile-middle-content clearfix">
      <div class="col-md-6">
        <h3>Quelques mots pour me présenter ...</h3>
        <h4 style="margin-top:30px;">Les débuts d'une reconversion</h4>
        <p>
          Après avoir passé plus de 20 ans dans le Transport, il était temps de raccrocher la moto. J'ai alors décidé d'orienter ma reconversion professionnelle dans l'informatique et plus précisément le Web, secteur qui me passionne depuis toujours. J'ai donc candidaté à la Wild Code School où j'ai été admis pour la session Août 2015 - Janvier 2016. Motivé à 300% j'ai également suivi les cours et tutoriels OpenClassroom afin de préparer au mieux cette formation.
        </p>
        <p>Pendant ces 5 mois, je me suis orienté Ruby et Ruby on Rails. Ayant toujours soif d'apprendre, je souhaite, bien sur continuer sur Rails, mais aussi apprendre jQuery et Javascript, langages indispensables pour animer mes applications web.
        </p>
        <h4 style="margin-top:30px;">L'aboutissement d'une reconversion</h4>
        <p>
          A la sortie de la Wild Code School, j'ai fais un stage de 4 mois chez Poneo, une porteuse de projet. Pas d'équipe de développement, juste ma volonté et débrouillardise. A l'issue de ces quatres
          mois, Loic Boutet, d'hexagonal Consulting, m'a recruté en freelance afin de parfaire ma formation et de monter en compétences sur un projet interne. Au programme, Rails 5, des tests et encore des tests, Hyperloop (anciennement ReactRB), Sidekiq et bien d'autres choses...<br>
          J'ai également créé des sites internet en parallèle dont un sous LocomotiveCMS.<br>
          L'aventure continue !!!! 
        </p>
      </div>
      <div class="col-md-6">
        <div class="prof-personal-details">
          <h4>Details personnel</h4>
          <div>
            <p class="light"><b><i class="fa fa-user"></i>Nom :</b> Eric Merlin</p>
            <p class="dark"><i class="fa fa-map-marker"></i><b>Adresse :</b> 28120 Illiers-Combray</p>
            <p class="light"><i class="fa fa-envelope"></i><b>Email :</b> eric.merlin3@gmail.com</p>
            <p class="dark"><i class="fa fa-mobile"></i><b>Portable :</b> 06.26.63.31.47</p>
            <p class="light"><i class="fa fa-github"></i><b>Github :</b> <%= link_to "github.com/riquet28", 'https://github.com/riquet28', :target => "_blank" %></p>
            <p class="dark"><i class="fa fa-linkedin"></i><b>Linkedin : </b><%= link_to "linkedin.com/in/eric-merlin", 'https://fr.linkedin.com/in/eric-merlin-563464101', :target => "_blank" %></p>
          </div>
        </div>
      </div>
    </article>

app/views/shared/_footer.html.erb
<footer class="footer-area">
  <div class="testimonial-area">
    <div class="testimonial-solid">
      <div class="container">
        <div id="carousel-example-generic" class="carousel slide" data-ride="carousel">
          <ol class="carousel-indicators hidden-xs">
            <li data-target="#quote-carousel" data-slide-to="0" class="active"><%= image_tag(("mathieu.jpg"), :class => "img-responsive") %>
            </li>
            <li data-target="#quote-carousel" data-slide-to="1"><%= image_tag(("amelie.jpg"), :class => "img-responsive") %>
            </li>
            <li data-target="#quote-carousel" data-slide-to="2"><%= image_tag(("celine.jpg"), :class => "img-responsive") %>
            </li>
            <li data-target="#quote-carousel" data-slide-to="3"><%= image_tag(("cyrille.jpg"), :class => "img-responsive") %>
            </li>
            <li data-target="#quote-carousel" data-slide-to="4"><%= image_tag(("thierry.jpg"), :class => "img-responsive") %>
            </li>
          </ol>
          <div class="carousel-inner">
            <div class="item active">
              <p>""Eric est une personne qui ne renonce devant rien et qui à réussi à mener tous ses projets à bien au court de la formation aussi bien ceux proposé par l’école que ceux qu’il s’est imposé.<br>Une vrai réussite, pour quelqu’un de déterminé depuis les premiers jours et qui ira sans aucun doute très loin."</p>
              <p>
                <%= link_to 'https://fr.linkedin.com/in/carbonelm', :target => "_blank" do %>
                  <span class="linkelien">- Mathieu C., Formateur Ruby, Wild Code School -</span>
                <% end %>
              </p>
            </div>
            <div class="item">
              <p>"Eric est une personne avec qui j'ai vraiment apprécié travailler. Extrêmement persévérant il ne renonce jamais et trouve toujours une solution. Il est taillé pour le développement et s'épanoui dans ce domaine."</p>
              <p>
                <%= link_to 'https://fr.linkedin.com/in/amelienadalini/en', :target => "_blank" do %>
                  <span class="linkelien">- Amélie N., Web développeur Ruby, WCS 2ème promo -</span>
                <% end %>
              </p>
            </div>
            <div class="item">
              <p>"Éric est une personne aimable, qui sait travailler en groupe. Il est consciencieux et aime le travail bien fait."</p>
              <p>
                <%= link_to 'https://fr.linkedin.com/in/c%C3%A9line-langlade-24a22382', :target => "_blank" do %>
                  <span class="linkelien">- Céline L., Web développeur Php, WCS 2ème promo -</span>
                <% end %>
              </p>
            </div>
            <div class="item">
              <p>"Au cours de ma formation j'ai pu travailler pendant plusieurs semaines avec Eric. C'est une personne agréable et organisée dans son travail. De part ses nombreuses connaissances, sa motivation et sa bonne humeur il est un moteur pour l'équipe. J'ai énormément appris à ses cotés et espère par la suite retravailler avec lui sur un projet commun !"</p>
              <p>
                <%= link_to 'https://fr.linkedin.com/in/cyrille-gross-12893b106', :target => "_blank" do %>
                  <span class="linkelien">- Cyrille G., Web développeur Php, WCS 2ème promo -</span>
                <% end %>
              </p>
            </div>
            <div class="item">
              <p>"J'ai beaucoup apprécié collaborer avec Eric lors de la formation à la Wild Code school. C'est quelqu'un de passionné et passionnant, rigoureux, qui aime le travail bien fait et sur qui l'on peut compter."</p>
              <p class="linkelien-a">
                <%= link_to 'https://fr.linkedin.com/in/thierrydamey', :target => "_blank" do %>
                  <span class="linkelien">- Thierry D., Web développeur Php, WCS 2ème promo -</span>
                <% end %>
              </p>
            </div>
          </div>
            <!-- Carousel Buttons Next/Prev -->
            <a data-slide="prev" href="#carousel-example-generic" class="left carousel-control"><i class="fa fa-chevron-left"></i></a>
            <a data-slide="next" href="#carousel-example-generic" class="right carousel-control"><i class="fa fa-chevron-right"></i></a>
        </div>
      </div>
    </div>
  </div>
  <div class="copy-content">2016 Eric Merlin | Freelance Ruby on Rails | 2ème promo WCS La Loupe</div>
</footer>

app/views/shared/_header.html.erb
<header class="header-area">
  <div class="container">
    <div class="header-outer clearfix">
      <div class="logo clearfix"> <span>Eric Merlin</span> <a href="#" class="nav-toggle"><i class="fa fa-bars"></i></a>
      </div>
      <nav class="navigation-area">
        <ul>
          <li><%= link_to "<i class='fa fa-home'></i>ACCUEIL".html_safe, root_path, class: ("active" if current_page?(root_path))%></li>
          <li><%= link_to "<i class='fa fa-user'></i>MON PROFIL".html_safe, profil_path, class: ("active" if current_page?(profil_path)) %></li>
          <li><%= link_to "<i class='fa fa-file-text'></i>MON CV".html_safe, moncv_path, class: ("active" if current_page?(moncv_path)) %></li>
          <li><%= link_to "<i class='fa fa-code'></i>MES PROJETS".html_safe, projets_path, class: ("active" if current_page?(projets_path)) %></li>
          <li><%= link_to "<i class='fa fa-envelope'></i>CONTACT".html_safe, new_contact_path, class: ("active" if current_page?(new_contact_path)) %></li>
        </ul>
      </nav>
    </div>
  </div>
</header>